# Generated by Django 5.0.2 on 2024-11-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('merek', models.CharField(max_length=100)),
                ('nirkabel', models.BooleanField(default=False)),
                ('surround_sound', models.BooleanField(default=False)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stok', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='KabelKonektor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('merek', models.CharField(max_length=100)),
                ('tipe_kabel', models.CharField(choices=[('HDMI', 'HDMI'), ('USB', 'USB'), ('Ethernet', 'Ethernet'), ('Lainnya', 'Lainnya')], max_length=100)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stok', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('merek', models.CharField(max_length=100)),
                ('tipe', models.CharField(choices=[('Mekanis', 'Mekanis'), ('Membran', 'Membran')], max_length=100)),
                ('lampu_latarm', models.BooleanField(default=False)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stok', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('merek', models.CharField(max_length=100)),
                ('resolusi', models.CharField(max_length=50)),
                ('ukuran_inci', models.DecimalField(decimal_places=1, max_digits=4)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stok', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('merek', models.CharField(max_length=100)),
                ('nirkabel', models.BooleanField(default=False)),
                ('dpi', models.PositiveIntegerField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stok', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Webcam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('merek', models.CharField(max_length=100)),
                ('resolusi', models.CharField(max_length=50)),
                ('frame_rate', models.PositiveIntegerField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stok', models.PositiveIntegerField()),
            ],
        ),
    ]
