# Generated by Django 5.1.3 on 2024-11-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peripheral', '0002_rename_nirkabel_headset_mikrofon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headset',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='headset',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='keyboard',
            name='lampu_latarm',
        ),
        migrations.RemoveField(
            model_name='keyboard',
            name='tipe',
        ),
        migrations.RemoveField(
            model_name='mouse',
            name='dpi',
        ),
        migrations.RemoveField(
            model_name='mouse',
            name='nirkabel',
        ),
        migrations.RemoveField(
            model_name='webcam',
            name='frame_rate',
        ),
        migrations.RemoveField(
            model_name='webcam',
            name='resolusi',
        ),
        migrations.AddField(
            model_name='keyboard',
            name='fitur',
            field=models.CharField(choices=[('Basic', 'Basic (No Backlight)'), ('Backlit', 'Single Color Backlit'), ('RGB', 'RGB Backlit'), ('RGB-Pro', 'RGB + Macro Keys')], default='Basic', max_length=50),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='jenis_switch',
            field=models.CharField(choices=[('Membran', 'Membran'), ('Mecha-Membrane', 'Mecha-Membrane'), ('Mechanical-Blue', 'Mechanical Blue Switch'), ('Mechanical-Red', 'Mechanical Red Switch'), ('Mechanical-Brown', 'Mechanical Brown Switch'), ('Optical', 'Optical Switch')], default='Membran', max_length=50),
        ),
        migrations.AddField(
            model_name='mouse',
            name='dpi_maksimum',
            field=models.PositiveIntegerField(choices=[(800, '800 DPI'), (1600, '1600 DPI'), (3200, '3200 DPI'), (6400, '6400 DPI'), (12000, '12000 DPI'), (16000, '16000 DPI'), (20000, '20000 DPI'), (25600, '25600 DPI')], default=800, help_text='Dots Per Inch maksimum yang didukung'),
        ),
        migrations.AddField(
            model_name='mouse',
            name='jenis_koneksi',
            field=models.CharField(choices=[('Wireless', 'Wireless'), ('Wired', 'Wired'), ('Hybrid', 'Wireless + Wired')], default='Wired', max_length=50),
        ),
        migrations.AddField(
            model_name='webcam',
            name='fps_maksimum',
            field=models.PositiveIntegerField(choices=[(30, '30 FPS'), (60, '60 FPS'), (120, '120 FPS')], default=30),
        ),
        migrations.AddField(
            model_name='webcam',
            name='resolusi_video',
            field=models.CharField(choices=[('720p', 'HD (1280x720)'), ('1080p', 'Full HD (1920x1080)'), ('2K', 'QHD (2560x1440)'), ('4K', 'Ultra HD (3840x2160)')], default='1080p', max_length=50),
        ),
        migrations.AlterField(
            model_name='headset',
            name='harga',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='kabelkonektor',
            name='harga',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='harga',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='harga',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='resolusi',
            field=models.CharField(choices=[('1366x768', 'HD (1366x768)'), ('1920x1080', 'Full HD (1920x1080)'), ('2560x1440', 'QHD (2560x1440)'), ('3840x2160', '4K (3840x2160)'), ('5120x2880', '5K (5120x2880)'), ('7680x4320', '8K (7680x4320)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='harga',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='webcam',
            name='harga',
            field=models.PositiveIntegerField(),
        ),
    ]
